name: Hello World

on:
  push:

jobs:
  say-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List Current Directory
        run: ls -a
      - name: List Project Directory
        run: ls ${{ github.workspace }}
      - name: Hello World Message
        run: echo 'Hello World'
  
