name: Test and Deploy Node App

on:
  push:
    branches:
    - 'main'

jobs:
  test-and-build:
    runs-on: linux-latest
    steps:
      - name: Setup Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Move To Backend
        run: cd backend
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build

  