name: Test and Build To Multiple Node Versions

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14,16,18]
    steps:
      - name: Set up Node Environment For ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ./backend/node_modules
          key: npm-backend-${{ matrix.node }}-${{ hashFiles('./backend/node_modules')}}
          restore-keys: |
            npm-backend-${{ matrix.node }}

      - name: Checkout Project Directory
        uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install
      
      - name: Test
        working-directory: ./backend
        run: npm run test

      - name: Build
        if: success()
        working-directory: ./backend
        run: npm run build

  notify:
    runs-on: ubuntu-latest
    needs: test-and-build
    if: success()
    steps:
      - name: Notify on Success
        run: echo "All tests and builds completed successfully on all Node versions!"
